### ISSUE TITLE
multiple strings

### ISSUE THREAD

**Issue by Porowl** [SmolBig/Text-Injector#3]
Missed screenshot 203. appears before the next one
![image](https://user-images.githubusercontent.com/13944746/37138428-db3bcd6a-225e-11e8-9292-4dbd0fdd2b16.png)
![image](https://user-images.githubusercontent.com/13944746/37138630-b118674a-225f-11e8-856d-1d45d3eec597.png)
![image](https://user-images.githubusercontent.com/13944746/37138706-030d01dc-2260-11e8-931c-1ac433d565d2.png)
![image](https://user-images.githubusercontent.com/13944746/37138796-4bc49642-2260-11e8-9cf1-86c71ee5c3e8.png)
![image](https://user-images.githubusercontent.com/13944746/37138821-637f18a2-2260-11e8-821c-227cc1da92e1.png)
![image](https://user-images.githubusercontent.com/13944746/37138946-deb73928-2260-11e8-93db-7fc0ee987250.png)
205 follows after 203
![image](https://user-images.githubusercontent.com/13944746/37139057-552998bc-2261-11e8-867a-9929d4025ae6.png)
![image](https://user-images.githubusercontent.com/13944746/37139453-c8171042-2262-11e8-9882-7a40fe88ffef.png)
![image](https://user-images.githubusercontent.com/13944746/37139611-6359fc90-2263-11e8-9d1f-1f7dda7eb7cc.png)
![image](https://user-images.githubusercontent.com/13944746/37140459-a0805f26-2266-11e8-8a4a-d0e1886bffaa.png)
![image](https://user-images.githubusercontent.com/13944746/37140624-38939882-2267-11e8-8364-57aabe5bc6a9.png)
Seems they share.

![image](https://user-images.githubusercontent.com/13944746/37140672-708d1ee8-2267-11e8-896f-1d584b063212.png)
This is at the village of outcast. Seems they share

![image](https://user-images.githubusercontent.com/13944746/37140885-0e797610-2268-11e8-8037-900536871b79.png)
when you throw the strange man's sign

![image](https://user-images.githubusercontent.com/13944746/37140918-30a8ec84-2268-11e8-803a-9322d43e5edb.png)

**Comment by SmolBig** [comment]
Awesome. I'll get right on it.

**Comment by SmolBig** [comment]
What location is 323? I don't remember where that is.

**Comment by Porowl** [comment]
![image](https://user-images.githubusercontent.com/13944746/37169990-73dbfc8e-22be-11e8-9027-e6d11f68087c.png)
that underground cave

**Comment by SmolBig** [comment]
Okay. Updating...

**Comment by SmolBig** [comment]
Do you have WinRAR? If so is it version 5 or higher?

**Comment by SmolBig** [comment]
Switching to Discord.
