### ISSUE TITLE
123/Bomb shop/134

### ISSUE THREAD

**Issue by Porowl** [SmolBig/Text-Injector#4]
![image](https://user-images.githubusercontent.com/13944746/37170082-b891ac5c-22be-11e8-9ca5-c7ec11791197.png)
![image](https://user-images.githubusercontent.com/13944746/37170112-cb1e8214-22be-11e8-94d9-360d95957ad4.png)
^ Not really. 
![image](https://user-images.githubusercontent.com/13944746/37170347-7589f968-22bf-11e8-93ff-aa1a3cbab82f.png)

**Comment by SmolBig** [comment]
added/corrected
